### ISSUE TITLE
Add oAuth methods

### ISSUE THREAD

**Issue by strk** [CartoDB/node-cartodb-redis#7]
method to fetch oauth access tokens objet from access_key.
Currently done by CartoDB-SQL-API directly:
https://github.com/CartoDB/CartoDB-SQL-API/blob/1.7.1/app/models/oauth.js#L143

**Comment by rochoa** [comment]
Done here: https://github.com/CartoDB/node-cartodb-redis/commit/b12bdaa5a2a60583b9b6c4cb1cf3653d27d8a756 :muscle:
